[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "watcher"
version = "0.0.1"

[tool.setuptools.packages]
find = {}

[project.scripts]
watch = "src.main:main"